site_name: Documentación holamundo_pyside6
site_url: https://di-mcgrawhill.github.io/holamundo-pyside6/
docs_dir: 'docs_src'
site_dir: 'docs'
nav:
    - Inicio: README.md
    - About: ABOUT.md
    - Descarga en pdf: PDF.md
theme: 
  name: material
plugins:
  - search
  - pdf-export
  - with-pdf:
      author: Ferran Cunyat Pellicer
      copyright: CC0 1.0 Universal
    #
      cover: true
      back_cover: false
      cover_title: Hola mundo! con PySide6
      cover_subtitle: Desarrollo interfaces - 2º DAM - Ed. McGrawHill
    #custom_template_path: TEMPLATES PATH
    #
      toc_title: Índice
    #heading_shift: false
      toc_level: 2
      ordered_chapter_level: 2
    #excludes_children:
    #    - 'release-notes/:upgrading'
    #    - 'release-notes/:changelog'
    #
    #exclude_pages:
    #    - 'bugs/'
    #    - 'appendix/contribute/'
    #convert_iframe:
    #    - src: IFRAME SRC
    #      img: POSTER IMAGE URL
    #      text: ALTERNATE TEXT
    #    - src: ...
    #two_columns_level: 3
    #
    #render_js: true
    #headless_chrome_path: headless-chromium
    #
      output_path: pdf/doc_holamundo_pyside6.pdf
    #enabled_if_env: ENABLE_PDF_EXPORT
    #
    #debug_html: true
    #show_anchors: true
    #verbose: true